[pytest]
addopts = -v -s --html=report.html --self-contained-html --alluredir=./temps --clean-alluredir
pythonpath = E:\PycharmProjects\APILoginProject
testpaths = tests
python_files = test_*.py
python_functions = test_*